FROM centos:centos7
#MAINTAINER 镜像作者
# MAINTAINER indifferent

RUN yum -y install gcc gcc-c++ gd-devel libxml2 libxml2-devel libcurl-devel \
    openssl openssl-devel curl curl-devel libjpeg libjpeg-devel libpng  \
    freestyle freestyle-devel pcre pcre-devel libxslt libxslt-devel bzip2 bzip2-devel m4 autoconf
ADD  php-7.2.31.tar.gz /tmp/
RUN cd /tmp/php-7.2.31 \
    && ./configure --prefix=/usr/local/php \
    --with-curl --with-freetype-dir --with-gd \
    --with-gettext --with-iconv-dir --with-kerberos \
    --with-libdir=lib64 --with-libxml-dir --with-mysqli \
    --with-openssl --with-pcre-regex --with-pdo-mysql \
    --with-pdo-sqlite --with-pear --with-png-dir \
    --with-jpeg-dir --with-xmlrpc --with-xsl --with-zlib \
    --with-bz2 --with-mhash --enable-fpm --enable-bcmath \
    --enable-libxml --enable-inline-optimization --enable-gd-native-ttf \
    --enable-mbregex --enable-mbstring --enable-opcache \
    --enable-pcntl --enable-shmop --enable-soap --enable-sockets \
    --enable-sysvsem --enable-sysvshm --enable-xml --enable-zip \
    && make && make install \
    && cp ./sapi/fpm/init.d.php-fpm /etc/init.d/php-fpm \
    && chmod a+x /etc/init.d/php-fpm \
    && groupadd -g 1001 www \
    && useradd -g 1001 -u 1001 www
#安装redis扩展
ADD  redis-5.2.2.tgz /tmp/
# RUN cd /tmp/redis-5.2.2/
# RUN /usr/local/php/bin/phpize
# RUN ./configure --with-php-config=/usr/local/php/bin/php-config 
# RUN make && make install
#安装yaf扩展
ADD  yaf-3.2.5.tgz /tmp/
# RUN cd /tmp/yaf-3.2.5
# RUN /usr/local/php/bin/phpize
# RUN ./configure --with-php-config=/usr/local/php/bin/php-config 
# RUN make && make install
#安装swoole扩展
ADD  swoole-4.5.2.tgz /tmp/
# RUN cd /tmp/swoole-4.5.2
# RUN /usr/local/php/bin/phpize
# RUN ./configure --with-php-config=/usr/local/php/bin/php-config 
# RUN make && make install
EXPOSE 9000
CMD ["/usr/local/php/sbin/php-fpm", "--nodaemonize"]
